Repository Automattic/WPCOM-Legacy-Redirector, pull requests merged in 2021-02, with the labels that each got.

#82 Refresh build configuration
  .travis.yml
  composer.json
Labels: Type: maintenance

#83 Add CODEOWNERS file
  .github/CODEOWNERS
Labels: Type: maintenance

#84 Add .editorconfig file
  .editorconfig
Labels: Type: maintenance

#85 Add .gitignore file
  .gitignore
Labels: Type: maintenance

#86 Create dependabot.yml
  .github/dependabot.yml
Labels: Type: maintenance

#78 Improve terminology to be more inclusive
  CHANGELOG.md
  includes/class-wpcom-legacy-redirector-ui.php
  includes/class-wpcom-legacy-redirector.php
  tests/test-redirects.php
Labels: Type: enhancement

#88 PHPUnit: Refresh
  phpunit.xml.dist
  tests/WpcomLegacyRedirectsTest.php
Labels: Type: maintenance

#90 Preservable Keys: Extract into method
  includes/class-wpcom-legacy-redirector.php
  tests/unit/PreservableParamsTest.php
Labels: Type: maintenance

#91 CLI: Show detailed error message on failed insert
  includes/class-wpcom-legacy-redirector-cli.php
Labels: Type: enhancement

#96 Refactor: Extract some code into separate classes.
  includes/class-capability.php
  includes/class-list-redirects.php
  includes/class-lookup.php
  includes/class-post-type.php
  includes/class-wpcom-legacy-redirector-cli.php
  includes/class-wpcom-legacy-redirector-ui.php
  includes/class-wpcom-legacy-redirector.php
  tests/integration/PostTypeTest.php
  tests/integration/RedirectsTest.php
  tests/unit/PreservableParamsTest.php
  wpcom-legacy-redirector.php
Labels: Type: maintenance

#97 Tests: Add unit test structure for WP-CLI class
  composer.json
  tests/unit/CliTest.php
  tests/unit/bootstrap.php
Labels: Type: maintenance

#94 Bugfix/77 wpcom vip add role caps fix
  includes/class-capability.php
  includes/class-wpcom-legacy-redirector.php
  tests/integration/CapabilityTest.php
  tests/unit/CapabilityTest.php
Labels: Needs: tests, Type: bug

#98 Tests: Fix minor issues
  composer.json
  phpunit-integration.xml.dist
  phpunit.xml.dist
  tests/Integration/CapabilityTest.php
  tests/Integration/PostTypeTest.php
  tests/Integration/RedirectsTest.php
  tests/Integration/TestCase.php
  tests/Integration/bootstrap.php
  tests/Unit/CapabilityTest.php
  tests/Unit/CliTest.php
  tests/Unit/PreservableParamsTest.php
  tests/Unit/bootstrap.php
  tests/unit/CliTest.php
Labels: Type: maintenance

#101 Unit Tests: Disable code coverage by default
  .gitignore
  composer.json
  phpunit.xml.dist
Labels: Type: maintenance

#100 Insert redirect: allow return of inserted post ID
  includes/class-wpcom-legacy-redirector.php
  tests/Integration/RedirectsTest.php
Labels: Type: enhancement

#103 Update CODEOWNERS
  .github/CODEOWNERS
Labels: Type: maintenance
