Repository Automattic/WPCOM-Legacy-Redirector, pull requests merged in 2024-05, with the labels that each got.

#126 Increase minimum PHP, WordPress, and bump dev-dependencies
  .phpcs.xml.dist
  CHANGELOG.md
  README.md
  composer.json
  wpcom-legacy-redirector.php
Labels: Type: maintenance

#127 PHPUnit: Refresh config files
  composer.json
  phpunit-integration.xml.dist
  phpunit.xml.dist
Labels: Type: maintenance

#129 CI: Add unit tests
  .github/workflows/unit-tests.yml
  composer.json
Labels: Type: maintenance

#130 Fix some Coding Standards issues
  .phpcs.xml.dist
  composer.json
  includes/class-list-redirects.php
  includes/class-lookup.php
  includes/class-wpcom-legacy-redirector-cli.php
  includes/class-wpcom-legacy-redirector-ui.php
  includes/class-wpcom-legacy-redirector.php
  tests/Behat/FeatureContext.php
  tests/Integration/RedirectsTest.php
  tests/Unit/PreservableParamsTest.php
Labels: Type: maintenance

#102 fixing non-ASCII redirects from issue #42
  includes/class-lookup.php
  includes/class-utils.php
  includes/class-wpcom-legacy-redirector.php
  tests/Integration/LookupTest.php
  tests/Integration/RedirectsTest.php
  tests/Unit/MonkeyStubs.php
  tests/Unit/PreservableParamsTest.php
  tests/Unit/RedirectsTest.php
  tests/Unit/UtilsTest.php
  tests/Unit/bootstrap.php
  wpcom-legacy-redirector.php
Labels: Type: bug

#93 Bugfix/73 admin redirect save fix
  includes/class-lookup.php
  includes/class-utils.php
  includes/class-wpcom-legacy-redirector-ui.php
  includes/class-wpcom-legacy-redirector.php
  tests/Integration/LookupTest.php
  tests/Integration/RedirectsTest.php
Labels: Type: bug

#132 UI: Add Follow link
  includes/class-list-redirects.php
Labels: Type: enhancement
